openapi: 3.0.1
info:
  title: DojoExpress API
  description: API documentation for DojoExpress service.
  version: 1.0.0
servers:
  - url: http://localhost:{port}
    description: Local server
    variables:
      port:
        default: "3000"
paths:
  /getChain:
    get:
      summary: Get chain
      operationId: getChain
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  value:
                    type: object
  /stats:
    get:
      summary: Get stats
      operationId: getStats
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  value:
                    type: object
  /mapiCallback:
    post:
      summary: MAPI callback
      operationId: mapiCallback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /authenticate:
    post:
      summary: Authenticate user
      operationId: authenticate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                identityKey:
                  type: string
                addIfNew:
                  type: boolean
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  value:
                    type: object
  /copyState:
    post:
      summary: Copy state
      operationId: copyState
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                identityKey:
                  type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  value:
                    type: object
  /getCurrentPaymails:
    post:
      summary: Get current paymails
      operationId: getCurrentPaymails
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                identityKey:
                  type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  value:
                    type: array
                    items:
                      type: string
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
        code:
          type: string
        description:
          type: string
